table fact_budget
	lineageTag: 46d19362-ef07-45c1-b1d6-49b3c01b78b5

	column district
		dataType: string
		lineageTag: 80098428-86e9-4001-8da0-8cc3cbd38f45
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column line_item
		dataType: string
		lineageTag: dbd151f0-62c8-43b6-9c07-f732dbd9d8aa
		summarizeBy: none
		sourceColumn: line_item

		annotation SummarizationSetBy = Automatic

	column budget_amount
		dataType: double
		lineageTag: 7924610e-19d6-4d11-a583-fa2a7546a680
		summarizeBy: none
		sourceColumn: budget_amount

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 18b8e29b-919a-4b11-84bb-5df92e3a134a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	partition fact_budget = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolderPath & "fact_budget.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"district", type text}, {"line_item", type text}, {"budget_amount", type number}}),
				    #"Fixed date" = Table.TransformColumns(#"Changed Type", {{"date", each if _ = null or _ = "" then null else Date.FromText(_), type date}})
				in
				    #"Fixed date"

	annotation PBI_ResultType = Table
