table fact_billing
	lineageTag: 075f53eb-69e2-4f45-baf7-afaf89b15020

	column subscriber_id
		dataType: string
		lineageTag: e904a759-a92d-429d-961b-c291939982b8
		summarizeBy: none
		sourceColumn: subscriber_id

		annotation SummarizationSetBy = Automatic

	column billed_amount
		dataType: double
		lineageTag: 88616874-f7e3-461c-8896-a1db75f1fff5
		summarizeBy: none
		sourceColumn: billed_amount

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5820f5bc-ac12-4b25-ad4f-723cc055daba
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	partition fact_billing = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolderPath & "fact_billing.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"subscriber_id", type text}, {"billed_amount", type number}}),
				    #"Fixed date" = Table.TransformColumns(#"Changed Type", {{"date", each if _ = null or _ = "" then null else Date.FromText(_), type date}})
				in
				    #"Fixed date"

	annotation PBI_ResultType = Table
